
name: Build App

on:
    workflow_run:
        workflows: ["Lint Code"]
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Clonar el codigo
              uses: actions/checkout@v4

            - name: Usar Node.js 20
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Instalar Yarn
              run: npm install -g yarn

            - name: Instalar dependencias con yarn   
              run: yarn install --frozen-lockfile

            - name: Compilar la app con vite
              run: yarn build
              