name: React CI + Deploy Vite con Yarn
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
            - name: Clonar el codigo
              uses: actions/checkout@v4
            - name: Usar Node.js 20
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Instalar Yarn
              run: npm install -g yarn
            - name: Instalar dependencias con yarn   
              run: yarn install --frozen-lockfile
            - name: Compilar la app con vite
              run: yarn build

            - name: Hacer deploy a Github Pages
              run: yarn deploy
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}